# File: .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  # apt_packages:
  #   - openmpi-bin
  #   - libopenmpi-dev
  commands:
    - apt-get install openmpi-bin libopenmpi-dev
    - pip install mpi4py
    - pip install petsc petsc4py

python:
  install:
    # - requirements: openaerostruct/docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

  system_packages: true
