# File: .readthedocs.yaml

version: 2

python:
  install:
    - requirements: openaerostruct/docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
