# File: .readthedocs.yaml

version: 2

build:
  apt_packages:
    - openmpi-bin
    - libopenmpi-dev

python:
  install:
    - requirements: openaerostruct/docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
  system_packages: true
