sudo: false

os:
  - linux

language: generic

env:
- FORTRAN= PY=2.7
- FORTRAN= PY=3.6
- FORTRAN=1 PY=2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
- OS=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "MacOSX"; else echo "Linux"; fi)
- if [ "$OS" = "MacOSX" ] && [ "$MPI" ]; then brew install openmpi; fi
- if [ "$PY" = "2.7" ];  then wget "https://repo.continuum.io/miniconda/Miniconda2-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- if [ "$PY" = "3.6" ];  then wget "https://repo.continuum.io/miniconda/Miniconda3-latest-$OS-x86_64.sh" -O miniconda.sh; fi
- chmod +x miniconda.sh
- if [ "$OS" = "Linux" ]; then
    ./miniconda.sh -b  -p /home/travis/miniconda;
  fi
- if [ "$OS" = "MacOSX" ]; then
    ./miniconda.sh -b  -p /Users/travis/miniconda;
  fi
- PATHPREFIX=$(if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then echo "/Users/travis/miniconda/bin"; else echo "/home/travis/miniconda/bin"; fi)
- export PATH=$PATHPREFIX:$PATH

install:
- conda install --yes python=$PY numpy scipy nose $HDF5 sphinx mock swig pip
- pip install --upgrade pip;
- if [ "$OS" = "Linux" ]; then
    if [ "$PY" = "2.7" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-cp27-none-linux_x86_64.whl;
    elif [ "$PY" = "3.6" ]; then
        pip install https://openmdao.org/dists/pyoptsparse-1.0.0-py3-none-linux_x86_64.whl;
    fi
  fi
- pip install mpi4py;

- git clone https://github.com/OpenMDAO/pyoptsparse.git;
- cd pyoptsparse;
- python setup.py install;
- cd ..;

- pip install coverage
- pip install coveralls
- pip install --user travis-sphinx
- pip install testflo
- export PATH=$HOME/.local/bin:$PATH
#- pip install git+git://github.com/OpenMDAO/openmdao.git
- git clone https://github.com/OpenMDAO/openmdao.git
- cd openmdao;
- pip install -e .
- cd ..
# install openaerostruct itself
- pip install -e .

script:
- if [ "$FORTRAN" ]; then
    cd openaerostruct/fortran; make; cd ../..;
  fi
- export PYTHONPATH=$PYTHONPATH:$PWD
- testflo -n 1 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*;
- if [ "$FORTRAN" ]; then
    travis-sphinx build --source=openaerostruct/docs;
  fi

after_success:
- if [ "$FORTRAN" ]; then
    travis-sphinx deploy;
  fi
- coveralls
