os:
- linux

language: python

python:
  - 3.7
env:
  - PARALLELIZE=true

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
-  wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh;
- chmod +x miniconda.sh;
- ./miniconda.sh -b  -p /home/travis/miniconda;
- export PATH=/home/travis/miniconda/bin:$PATH;

install:
- conda install --yes python=$PY nose sphinx mock swig pip numpydoc;
- pip install --upgrade pip;

# install openaerostruct itself. NOTE: required packages (e.g. openmdao, numpy) are specified in setup.py.
- pip install -e .;

# install pyoptsparse
- git clone https://github.com/mdolab/pyoptsparse.git;
- cd pyoptsparse;
- python setup.py install;
- cd ..;

- pip install coverage;
- pip install coveralls;
- pip install testflo;
- export PATH=$HOME/.local/bin:$PATH;

# install and sphinx-travis
- pip install --user travis-sphinx;
- pip install redbaron

script:
- export PYTHONPATH=$PYTHONPATH:$PWD
- testflo -n 2 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*;
- cd openaerostruct/docs;
- travis-sphinx build --source=.;
- cd ../..;

after_success:
- cd openaerostruct/docs;
- travis-sphinx deploy;
- cd ../..;
- coveralls;
