os:
- linux

language: generic

env:
- PY=3.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev
    - libopenmpi-dev
    - openmpi-bin

before_install:
-  wget "https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" -O miniconda.sh;
- chmod +x miniconda.sh;
- ./miniconda.sh -b  -p /home/travis/miniconda;
- export PATH=/home/travis/miniconda/bin:$PATH;

install:
- conda install --yes python=$PY numpy scipy nose sphinx mock swig pip matplotlib numpydoc;
- pip install --upgrade pip;
- pip install mpi4py;

# install pyoptsparse
- git clone https://github.com/mdolab/pyoptsparse.git;
- cd pyoptsparse;
- python setup.py install;
- cd ..;

- pip install coverage;
- pip install coveralls;
- pip install testflo==1.3.6;
- export PATH=$HOME/.local/bin:$PATH;

# install openmdao and sphinx-travis
- pip install openmdao
- pip install --user travis-sphinx;
- pip install redbaron

# install openaerostruct itself
- pip install -e .;

script:
- export PYTHONPATH=$PYTHONPATH:$PWD
- testflo -n 1 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*;
- cd openaerostruct/docs;
- travis-sphinx build --source=.;
- cd ../..;

after_success:
- travis-sphinx deploy;
- coveralls;
