name: Flake8 code style check

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # OAS dependencies are specified in setup.py.
    - name: Install OAS and its dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .[test]

    # code style check by flake8
    - name: Code style (flake8)
      run: |
        pip install flake8==3.9.2
        python -m flake8 openaerostruct --append-config ./.github/.flake8 --count --show-source --statistics
