name: OAS build

# This workflow runs all unit and regression tests, as well as coveralls.
# On the pull-request events, this workflow runs OAS tests, checks code format by flake8/black, and builds the docs.
# On the push-to-master events, it also deploys the docs.

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  # --- run OAS unit and regression tests ---
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # OAS dependencies are specified in setup.py.
    - name: Install OAS and its dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .[test]
        pip install coverage coveralls     # for coveralls

    # we need pySpline/pyGeo to run FFD tests.
    - name: Install pySpline and pyGeo
      run: |
        sudo apt-get install openmpi-bin libopenmpi-dev
        pip install mpi4py
        git clone https://github.com/mdolab/pyspline.git
        cd pyspline
        cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk
        make
        pip install -e .
        cd ..
        git clone https://github.com/mdolab/pygeo.git
        pip install -e ./pygeo

    - name: Run tests
      env:
        OMPI_MCA_btl: ^openib   # prevent OpenMPI warning messages
      run: |
        cd openaerostruct
        testflo -n 2 openaerostruct --coverage --coverpkg openaerostruct --cover-omit \*tests/\* --cover-omit \*docs/\*

    - name: Run coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cd openaerostruct
        coveralls --service=github --rcfile=../.coveragerc;

  # --- code style check by flake8 ---
  flake8:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # use both MDO Lab standard config
    - name: Code style (flake8)
      run: |
        pip install flake8==3.9.2
        wget https://raw.githubusercontent.com/mdolab/.github/master/.flake8 -O .flake8_mdolab
        python -m flake8 openaerostruct --append-config .flake8_mdolab --append-config .github/.flake8_oas_specific --count --show-source --statistics

  # --- code format check by black ---
  black:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # code format check by black
    - name: Code format (black)
      run: |
        pip install black==21.6b0
        black openaerostruct --check --diff -l 120 --target-version py38

  # --- documentation build ---
  docs-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # build docs
    - name: Build docs
      run: |
        python -m pip install --upgrade pip wheel
        pip install .[docs]
        cd openaerostruct/docs
        make clean
        make html

    # deploy docs only when we're pushing to the master branch.
    - name: Commit doc changes
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      run: |
        git clone https://github.com/mdolab/OpenAeroStruct.git --branch gh-pages --single-branch gh-pages
        cp -r ./openaerostruct/docs/_build/html/* gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true

    - name: Push changes to gh-pages
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}