name: OAS release

# Pushes any new releases to pypi

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*


jobs:
  pypi:
    uses: mdolab/.github/.github/workflows/pypi.yaml@main
    secrets: inherit
